version: "3"
services:
    mysql57:
        image: ottar63/rpi-mysql-atlassian
        deploy: 
            placement:
                constraints: [node.role == manager]
        ports:
            - "3306:3306"
        networks:
            - atlassian
        volumes:
            - "/opt/mysql/data:/var/lib/mysql"
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        container_name: mysql57
    jira:
        image: ottar63/rpi-mysql-jira
        ports:
            - "8080:8080"
        deploy:
            replicas: 1
            placement:
                constraints: [node.role == manager ]
        networks:
            - atlassian
        container_name: jira
        links:
            - mysql57
        volumes:
            - "/data/atlassian/jira_home:/var/atlassian/jira"
        depends_on:
            - "mysql57"
        #entrypoint: bash
#
#    portainer:
#        image: portainer/portainer
#        command: -H tcp://tasks.agent:9001 --tlsskipverify
#        ports:
#            - "9000:9000"
#        volumes:
#            - portainer_data:/data
#        networks:
#            - mariadb
#        deploy:
#            mode: replicated
#            replicas: 1
#            placement:
#                constraints: [node.role == manager]
networks:
    atlassian:
